docker:
  config_files:
  - .bashrc
  config_source: project_template
  container_name: dev-container
  enhanced_mode: true
  image: ubuntu:20.04
  ports:
  - 8080:8080
  - 8888:8888
  - 6006:6006
  shell_config:
    path: /bin/bash
    type: bash
  system_config:
    ipc_mode: host
    network_mode: host
    privileged: true
    restart_policy: always
    security_opt:
    - seccomp=unconfined
    shm_size: 256g
    ulimit_core: -1
    uts_mode: host
  volumes:
  - /home:/home
  - /data1:/data1
  - /data2:/data2
  - /data3:/data3
  - /data4:/data4
  - /data:/data
  working_directory: /workspace
