auto_create: true
container_name: dev_environment
description: 通用开发环境
image: ubuntu:20.04
install_packages:
- curl
- wget
- git
- vim
- tmux
- zsh
network_mode: host
privileged: true
restart_policy: always
setup_commands:
- apt update && apt install -y curl wget git vim tmux zsh
- echo 'Development environment ready!'
template_type: development
volumes:
- /home:/home
- /tmp:/tmp
working_directory: /workspace
